def align(x,y):
    table = []
    for i in range(len(x)+1):
        table.append([])
        for j in range(len(y)+1):
            table[i].append(0)

            if i >0 and j >0:

                if x[i-1] == y[j-1]:

                    table[i][j] = table[i-1][j-1]+1
                else:
                    table[i][j] = max(table[i - 1][j - 1],table[i-1][j],table[i][j-1])
#    print(table)
    i = len(x)-1
    j = len(y)-1
    new_x = ''
    new_y = ''
    while i >=0 and j >=0:
        if x[i] == y[j]:
            if table[i+1][j+1] > max(table[i][j],table[i-1][j],table[i][j-1]):
                new_x = x[i]+new_x
                new_y = y[j]+new_y
                i-= 1
                j-= 1
        else:
            if table[i - 1][j - 1]+1 > max(table[i - 1][j] ,table[i][j-1]):
                new_x = x[i] + new_x
                new_y = y[j] + new_y
                i = i - 1
                j = j - 1
            else:
                if table[i-1][j]> table[i][j-1]:

                    new_x = x[i] + new_x
                    new_y = '-' + new_y
                    i = i - 1
                else:

                    new_x = '-' + new_x
                    new_y = y[j] + new_y
                    j = j - 1
    print(new_x)
    print(new_y)


s = 'DPAVSDTRDEPMCRKRPFCKKTHNFSCWVVQVMDQQLPMDMRAPTDRQQGKSSKPFGYNHRRDSQRVFTCSMGILGDCNKEQHNTKKICPAVWCSRYMWAPIHGTNNWEKMSDSQCLSFWEDMEPSMHDNMCVIAPCRNINLRSSKTLEWGYGPQWLIIRCQRQQMQLRRVREVQCPTLPRPAFSHHEYMIAPWHHDGEKRCVVCKFEPNLGCGLSKTEWPLDDRIWNRCQKSQTERPYRMGKTWCTKIKVDKYHQEWGTTADLMMRLTDKINEWNMYHIMEITIRQCPPLHGGGDMKVETWRWNMMWKLMPYDKPNQDFPFEFNNYTCGKMTVCLEWRMLLASLLRRIYICYYKKVIVPLCKQMSGVPRHPNDRWKYRTFNWTEPWTMQPTGPNTIWFQRHTDYPLGFYNYQFKILIIDYLMCSRNEVAHRQECCRLWIDQAVCMTSSKYPSMTLDYIAEIIMNADMTLNFRMMSAKRKYVLVSMFLHMCATWNSPPPTKWSFIVRSKILVCDNHCTPDRHSKRISNMGADDHFEYVYYYDMEPFPAMSGKNFVARLQKQEEKVYVDRCTNILSDADHQSWTMHGYGVYVADWTFAAAPDSIHQVDPYHCHKKKNLEAVVENWAWMPFYLFNGMHYWSTPGCWSWAWCFLWPDSNINYCQCNLRFSNRHLVGCAENFYMDAWMVISWPISKVCGFLHSTTKWMDPAADMPWAIPMVYKAENWPPDMVNYLNEFQFCTTIETYIYRTWCAWMLFADTSIYYCCGSPCERQTNHLFCVHGFTWKDWLCVCAIQGHCAFGIRLKANRAYFEMLWRNMRKYGHASLIWKNNVNCFHHPGYMTIHWYMNRRAMCFPHMI'
t = 'DPFRMFVSDTRDEPMDKRDDANDGKRPKCKKTHDFIVGSDNMCWLPMDMSAPLDRQQGKGSKRFQWYNHFLMNWRLECHHLSVRVFTCYAALQFPRMGIQHDQHATRGKEQHNVWCSRYMWRCNRHCSAPVPVKMGTNNWEKMSRWEDMEPSMHDNMCVIAPCRFINLPFWWLWPMCQARSYTLEYGPQPWKDLIIRCQRLLRRVREVQCHTLPRPAFSHHEYAIQPWHHDGEKRCVVCKFEPNLGCPTWELMDELSKTEYPLDDRIWNRCQKSQTERPYRRGKAAWCTKIKGTTHWLMMRLTDKINEWNMYHIMEPPLHGPVTDHVVVGDMKVETWVWNMMWKLMPYQIIGPGVWKVQSNYNNDFRNNYTCLEWRMLLACYLCKQSSGVPYHPNDRWKYRTFNWFKNRCKQMETMQPTGPFHMIWFQRDYPLGFYNYEFEFQNILIVMHRDECCRLWIDQAVCMTSSKYNSITWDYIDMTFNFCMMSAKRKYVLVRITWNSPPFITRSKILVYGKLDCCALKNNFNHCTPDRHISNMGADDHFEYELFWGSNYHTMEPFPAMSMKNFQGEKVYVDRCTNILSDADHQSFTMHGVYVPDQICIHQVDPYEAVMNWFYLFNGMHYLPPWVMFNSTPGCWSWANDQIPNQFMCFLWGDQCNLRGSNRGDYWCFSLDGCATKFYVDAWGVISWPISKVCGFLHSLTKWMSYPAADMPWVQETQSKRVDYTDGLPMVYKAENWGDKWPDMVHYLNEFQCRETYIYRKFIPWCAWIRICMARSVPWRFSIYYCCGSCCQCEFVMDMGYCHQAQFNHLFCTCHGFTWKCKKADHIQGHCARLKANRDYFEMLWRNCRKYGHEWSLIWINNVNCMHHPGQMTTHWYMNRRQMCFTHTI'
align(s,t)